import type { Metadata } from "next";
import { Open_Sans, Poppins } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import "./globals.css";
import Script from "next/script";
import Navbar from "@/components/Homepage/Navbar";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body
          className={`${poppins.variable} ${openSans.variable} antialiased`}
          >
          <Navbar />
          {children}
          <Toaster />
        </body>
      </html>
      <Script src="https://checkout.razorpay.com/v1/checkout.js" />
    </>
  );
}
